name: Coverage
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up CMake
        uses: lukka/get-cmake@v3.25.2
      - name: Configure and build CMake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
          buildDirectory: "${{ github.workspace }}/build"
      - name: Run CTest
        run: ctest --output-on-failure --test-dir ${{ github.workspace }}/build/test
      - name: Generate a code coverage report using gcovr
        run: |
          python3 -m pip install gcovr
          gcovr --exclude-directories build --exclude-directories test --html-details output.html
      - name: Upload coverage report to github
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: details.html
