name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: Set up CMake
        uses: lukka/get-cmake@v3.27.7
      - name: Configure CMake
        working-directory: "${{ github.workspace }}/src/hades_extensions"
        run: cmake --preset Debug
  clang-tidy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Run clang-tidy
        working-directory: "${{ github.workspace }}/src/hades_extensions"
        run: |
          find . -name compile_commands.json
          clang-tidy -p build-debug/compile_commands.json --quiet -extra-arg --std=c++20 ./**/*.cpp ./**/*.hpp
  cppcheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Run cppcheck
        working-directory: "${{ github.workspace }}/src/hades_extensions"
        run: |
          sudo apt-get install -y -q cppcheck
          cppcheck --enable=all --suppress=missingInclude --suppress=missingIncludeSystem --quiet ./include/ ./src/ ./tests/
  clang-format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Run clang-format
        working-directory: "${{ github.workspace }}/src/hades_extensions"
        run: find ./include ./src ./tests -type f \( -iname "*.cpp" -o -iname "*.hpp" \) -exec clang-format -i {} \;
