name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: Set up CMake
        uses: lukka/get-cmake@v3.27.7
      - name: Configure CMake
        working-directory: "${{ github.workspace }}/src/hades_extensions"
        run: cmake --preset Debug
  clang-tidy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Run clang-tidy
        working-directory: "${{ github.workspace }}/src/hades_extensions"
        run: clang-tidy -p build-debug/compile_commands.json ./**/*.cpp ./**/*.hpp
  cppcheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Run cppcheck
        working-directory: "${{ github.workspace }}/src/hades_extensions"
        run: cppcheck --enable=all --suppress=missingInclude --suppress=missingIncludeSyste --quiet ./**/*.cpp ./**/*.hpp
  clang-format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Run clang-format
        working-directory: "${{ github.workspace }}/src/hades_extensions"
        run: find . -regex '.*\.\(cpp\|hpp\)' -exec clang-format -style=file -i {} \;
